question_data = [
{"text": "A slug's blood is green.", "answer": "True"},
{"text": "The loudest animal is the African Elephant.", "answer": "False"},
{"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
{"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
{"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
{"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
{"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
{"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
{"text": "Google was originally called 'Backrub'.", "answer": "True"},
{"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
{"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
{"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
  {"text": "Is the Earth round?", "answer": "true"},
  {"text": "Does 2 + 2 equal 5?", "answer": "false"},
  {"text": "Is the sun a star?", "answer": "true"},
  {"text": "Can humans breathe underwater without equipment?", "answer": "false"},
  {"text": "Is 7 a prime number?", "answer": "true"},
  {"text": "Does the moon emit its own light?", "answer": "false"},
  {"text": "Is water composed of hydrogen and oxygen?", "answer": "true"},
  {"text": "Is a triangle a four-sided shape?", "answer": "false"},
  {"text": "Is Mount Everest the tallest mountain on Earth?", "answer": "true"},
  {"text": "Do all birds have teeth instead of beaks?", "answer": "false"},
  {"text": "Is the chemical symbol for gold Au?", "answer": "true"},
  {"text": "Is a kilometer longer than a mile?", "answer": "false"},
  {"text": "Do penguins live in the Arctic?", "answer": "false"},
  {"text": "Is the Pacific Ocean the largest ocean?", "answer": "true"},
  {"text": "Is a square a type of rectangle?", "answer": "true"},
  {"text": "Does the Earth revolve around the moon?", "answer": "false"},
  {"text": "Is a century 100 years?", "answer": "true"},
  {"text": "Is a spider an insect?", "answer": "false"},
  {"text": "Is the freezing point of water 0°C at sea level?", "answer": "true"},
  {"text": "Do all mammals lay eggs?", "answer": "false"},
  {"text": "Is the capital of France Paris?", "answer": "true"},
  {"text": "Is the number 1 a prime number?", "answer": "false"},
  {"text": "Does the human body have 206 bones?", "answer": "true"},
  {"text": "Is a byte equal to 8 bits?", "answer": "true"},
  {"text": "Is the Sahara Desert in South America?", "answer": "false"},
  {"text": "Is photosynthesis performed by plants?", "answer": "true"},
  {"text": "Is a leap year 366 days long?", "answer": "true"},
  {"text": "Do all planets have moons?", "answer": "false"},
  {"text": "Is the speed of light approximately 300,000 km/s?", "answer": "true"},
  {"text": "Is a hexagon a five-sided shape?", "answer": "false"},
  {"text": "Is the inventor of the telephone Alexander Graham Bell?", "answer": "true"},
  {"text": "Do crocodiles live in saltwater?", "answer": "true"},
  {"text": "Is the smallest country Vatican City?", "answer": "true"},
  {"text": "Is a negative number always less than zero?", "answer": "true"},
  {"text": "Is the Great Wall of China visible from space?", "answer": "false"},
  {"text": "Is a dolphin a mammal?", "answer": "true"},
  {"text": "Is the boiling point of water 100°C at sea level?", "answer": "true"},
  {"text": "Is a circle a polygon?", "answer": "false"},
  {"text": "Is the currency of Japan the yen?", "answer": "true"},
  {"text": "Do all snakes have legs?", "answer": "false"},
  {"text": "Is the largest planet in our solar system Jupiter?", "answer": "true"},
  {"text": "Is a right angle 90 degrees?", "answer": "true"},
  {"text": "Is Antarctica a desert?", "answer": "true"},
  {"text": "Is the Mona Lisa painted by Michelangelo?", "answer": "false"},
  {"text": "Is DNA a double helix?", "answer": "true"},
  {"text": "Is the equator the longest latitude line?", "answer": "true"},
  {"text": "Is a whale a fish?", "answer": "false"},
  {"text": "Is the atomic number of carbon 6?", "answer": "true"},
  {"text": "Is the Amazon River in Africa?", "answer": "false"},
  {"text": "Is the theory of relativity proposed by Einstein?", "answer": "true"},
  {"text": "Is a kilometer equal to 1000 meters?", "answer": "true"},
  {"text": "Is a virus a living organism?", "answer": "false"},
  {"text": "Is the largest bone in the human body the femur?", "answer": "true"},
  {"text": "Is a pentagon a six-sided shape?", "answer": "false"},
  {"text": "Is the capital of Australia Canberra?", "answer": "true"},
  {"text": "Do all fish have gills?", "answer": "true"},
  {"text": "Is the shortest war in history 38 minutes long?", "answer": "true"},
  {"text": "Is a full moon visible every night?", "answer": "false"},
  {"text": "Is a liter equal to 1000 milliliters?", "answer": "true"},
  {"text": "Is the sun larger than the Earth?", "answer": "true"},
  {"text": "Is the inventor of the light bulb Thomas Edison?", "answer": "true"},
  {"text": "Is a square root of 16 equal to 8?", "answer": "false"},
  {"text": "Is the smallest planet in our solar system Mercury?", "answer": "true"},
  {"text": "Is a parallelogram a four-sided shape?", "answer": "true"},
  {"text": "Is the human heart a muscle?", "answer": "true"},
  {"text": "Is the Nile River the longest river in the world?", "answer": "true"},
  {"text": "Is a year on Jupiter shorter than a year on Earth?", "answer": "false"},
  {"text": "Is a cube a three-dimensional shape?", "answer": "true"},
  {"text": "Is the chemical symbol for oxygen O?", "answer": "true"},
  {"text": "Is a triangle always equilateral?", "answer": "false"},
  {"text": "Is the capital of Brazil Brasília?", "answer": "true"},
  {"text": "Do all animals need oxygen to survive?", "answer": "false"},
  {"text": "Is the Pythagorean theorem used in geometry?", "answer": "true"},
  {"text": "Is the largest organ in the human body the skin?", "answer": "true"},
  {"text": "Is the Eiffel Tower in London?", "answer": "false"},
  {"text": "Is a day on Earth 24 hours long?", "answer": "true"},
  {"text": "Is a rhombus a type of square?", "answer": "false"},
  {"text": "Is the currency of the United States the dollar?", "answer": "true"},
  {"text": "Is a comet made of ice and dust?", "answer": "true"},
  {"text": "Is a rectangle a three-sided shape?", "answer": "false"},
  {"text": "Is the human brain responsible for thinking?", "answer": "true"},
  {"text": "Is a shark a mammal?", "answer": "false"},
  {"text": "Is the capital of Russia Moscow?", "answer": "true"},
  {"text": "Is a kilometer shorter than a mile?", "answer": "true"},
  {"text": "Is the sun at the center of our solar system?", "answer": "true"},
  {"text": "Is a trapezoid a type of triangle?", "answer": "false"},
  {"text": "Is the element hydrogen the lightest element?", "answer": "true"},
  {"text": "Is the Great Barrier Reef in Australia?", "answer": "true"},
  {"text": "Is a year 365 days long in a non-leap year?", "answer": "true"},
  {"text": "Is a bat a bird?", "answer": "false"},
  {"text": "Is the capital of China Beijing?", "answer": "true"},
  {"text": "Is a straight angle 180 degrees?", "answer": "true"},
  {"text": "Is the Statue of Liberty in New York?", "answer": "true"},
  {"text": "Is a jellyfish a fish?", "answer": "false"},
  {"text": "Is the chemical formula for water H2O?", "answer": "true"},
  {"text": "Is the moon larger than the Earth?", "answer": "false"},
  {"text": "Is a light-year a measure of distance?", "answer": "true"},
  {"text": "Is the capital of India New Delhi?", "answer": "true"}

]